import Head from "next/head";
import Image from "next/image";
import Card from "../components/Card";
import Navbar from "../components/Navbar";

export default function Home() {
  const title = "Product Roadmap";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar title="Product Roadmap" />

      <div class="flex flex-wrap justify-evenly">
        <Card />
        <Card />
        <Card />
        <Card />
      </div>
    </>
  );
}
