import Head from "next/head";
import Card from "../components/Card";
import Navbar from "../components/Navbar";
import Modal from "../components/Modal";

export default function Home() {
  return (
    <>
      <Modal/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar title="Product Roadmap" />
      <div class="flex flex-wrap justify-evenly">
        <Card
          groupname="Group Task 1"
          date="January - March"
          color="emerald"
          tasklist={[
            {
              name: "Re-design the zero-g doggie bags. No more spills!",
              progress: 100,
            },
          ]}
        />
        <Card
          groupname="Group Task 2"
          date="April - June"
          color="yellow"
          tasklist={[
            {
              name: "Bundle interplanetary analytics for improved transmission",
              progress: 30,
            },
          ]}
        />
        <Card
          groupname="Group Task 3"
          date="July - September"
          color="red"
          tasklist={[
            {
              name: "Data Migration: Perfomance & Culture End Game",
              progress: 60,
            },
          ]}
        />
        <Card
          groupname="Group Task 4"
          date="October - December"
          color="teal"
          tasklist={[
            {
              name: "Bundle interplanetary analytics for improved transmission",
              progress: 20,
            },
          ]}
        />
      </div>
    </>
  );
}
