import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

export default function Home() {
  const title = "Product Roadmap";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar title="Product Roadmap" />
      <div class="flex flex-wrap justify-around">
        <div className="bg-white shadow p-4 m-2 border-2 rounded border-red-300">
        <div class="border-2 border-red-300 rounded w-fit">
          <h3 className="text-[12px] px-2 font-medium text-red-400">Group Task 1</h3>
        </div>
          <div className="text-gray-700 font-bold text-xs pt-2">
            January - March
          </div>
        </div>
      </div>
    </>
  );
}
